### ISSUE TITLE
webpack module not found

### ISSUE THREAD

**Issue by jbb352** [Microsoft/PowerBI-Angular#11]
I am using angular-fullstack 4.0 and have added angular-powerbi to the project.  I am getting the following error.

Error: [ng:areq] Argument 'module' is not a function, got Object

I have included angular-powerbi in my webpack config
and added import powerbi from 'angular-powerbi'; to my app.js
and included powerbi in the angular.module

angular.module('myapp', [
    ngCookies, ngResource, ngSanitize, 'btford.socket-io', uiRouter, ngMaterial, ngMaterialIcons, match, powerbi
])

any help would be greatly appreciated.

**Comment by mattmazzola** [comment]
I'm not familiar with angular-fullstack, but `angular.module` is standard way to create modules and list their dependencies.  Perhaps you have a syntax error somewhere. 

The docs here show the signature:
https://docs.angularjs.org/api/ng/function/angular.module

I'm assuming this is a problem with your project setup rather than an issue with the our library.

**Comment by jbb352** [comment]
Yes, I expect it is an issue with the project.  I have however added other modules in the same way and they are working so wondering if there was something I am missing.

**Comment by jbb352** [comment]
got it :)
needed to add some single quotes around the powerbi module above.  Haven't worked out why I need to do this for some modules and not others, but that's just my novice level on angular.  
Thanks for the assistance.
